
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-HipochondriAI}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hypochondriai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-HipochondriAI}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hypochondriai_backend
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-HipochondriAI}
      - DB_SUPERUSER_USERNAME=${DB_SUPERUSER_USERNAME}
      - DB_SUPERUSER_PASSWORD=${DB_SUPERUSER_PASSWORD}
      - DB_SUPERUSER_EMAIL=${DB_SUPERUSER_EMAIL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-eu-central-1}
      - MODEL_ID=${MODEL_ID:-anthropic.claude-3-5-sonnet-20240620-v1:0}
      - MODEL_PROVIDER=${MODEL_PROVIDER:-bedrock_converse}
      - MAX_TOKENS=${MAX_TOKENS:-1000}
      - TEMPERATURE=${TEMPERATURE:-0.3}
      - TOP_P=${TOP_P:-0.4}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - API_PREFIX=${API_PREFIX:-/api/v1}
      - APP_NAME=${APP_NAME:-HypochondriAI - Health anxiety specialist}
      - APP_VERSION=${APP_VERSION:-0.1.0}
      - APP_DESCRIPTION=${APP_DESCRIPTION:-AI Agent offering personalized support for people struggling with health anxiety}
    ports:
      - "8000:8000"
    networks:
      - hypochondriai-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_SUPERUSER_NAME=${DB_SUPERUSER_USERNAME}
    container_name: hypochondriai_frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - hypochondriai-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  hypochondriai-network:
    driver: bridge
