[tool.ruff]
# Target Python version - adjust to match your project's Python version
target-version = "py39"

# Set the line length to match your project's style
line-length = 88

# Specify the directories to lint
src = ["app", "tests"]  # Adjust these paths to match your project structure

# Select the rule sets to enable
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "N",    # pep8-naming
    "PL",   # pylint
    "RUF",  # Ruff-specific rules
]

# Rules to explicitly ignore
ignore = [
    # Add any rules you want to disable here
    "B008",  # Allow function calls in argument defaults (FastAPI Depends())
    "E501",  # Allow long lines in specific cases
    "F401",  # Allow unused imports in __init__.py
]

# Allow auto-fixing for all enabled rules
fixable = ["ALL"]
unfixable = []

# Exclude directories and files from linting
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "node_modules",
    "alembic",  # Exclude database migration files if you use alembic
]

# Sort imports configuration
[tool.ruff.isort]
known-first-party = ["app"]  # Replace with your FastAPI app package name

# Per-file rule overrides if needed
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in __init__ files
# "app/api/dependencies.py" = ["F821"]  # Example: Ignore undefined names in dependencies

# Mccabe complexity checker settings
[tool.ruff.mccabe]
max-complexity = 10  # Set your desired complexity threshold

[tool.ruff.format]
quote-style = "double" 
indent-style = "tab" 
line-ending = "auto" 